services:
  db:
    container_name: wirecraft_db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
